[package]
name = "poc-plpgsql-analyzer"
authors = ["Christoph Heiss <christoph.heiss@cybertec.at>"]
version = "0.1.0"
edition = "2021"
description = "Proof of concept for tooling to migrate PL/SQL code to PL/pgSQL written in Rust."
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/cybertec-postgresql/poc-plpgsql-analyzer"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "^7.1.1"
nom_locate = "^4.0.0"
thiserror = "^1.0.35"
wasm-bindgen = "^0.2.83"

[profile.release]
lto = true

[dev-dependencies]
datatest = "0.7.1"
pretty_assertions = "1.3.0"

[package.metadata.nix]
build = true
