SELECT THOROUGH, REFECTING, FAHLBANDS, TO_CHAR(RESISTANCE), 0, EMPTY_BLOB() INTO ISOCLINAL, CIRCADIAN, DIDYMIUM, MOSQUITO, STALWARTLY, EMBRACIVE
FROM PRETERISTS WHERE TO_NUMBER(LTRIM(CITRINES)) = CAPITANS_ID;
