name: Test TypeScript interface

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and test TypeScript interface
    runs-on: [self-hosted, Linux]
    container: node:18-bullseye
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          apt-get update \
          && apt-get install --assume-yes \
            curl binaryen gcc libssl-dev make pkg-config

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install wasm-pack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack

      - name: Install npm dependencies
        working-directory: ./tests/typescript
        run: npm clean-install

      - name: Execute Typescript tests
        working-directory: ./tests/typescript
        run: npm test

