name: Test TypeScript interface

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and test TypeScript interface
    runs-on: [self-hosted, Linux]
    container: registry.dc1.cybertec.at/docker-hub-proxy/library/node:18-bullseye
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          apt-get update \
          && apt-get install --assume-yes \
            curl binaryen gcc libssl-dev make pkg-config

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Cache npm test dependencies
        uses: actions/cache@v3
        id: cache-npm-test-deps
        continue-on-error: false
        with:
          path: ./tests/typescript/node_modules/
          key: ${{ runner.os }}-npm-${{ hashFiles('./tests/typescript/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install wasm-pack
        uses: baptiste0928/cargo-install@v1
        with:
          crate: wasm-pack
          version: "0.10.3"

      - name: Install npm test dependencies
        if: steps.cache-npm-test-deps.outputs.cache-hit != 'true'
        working-directory: ./tests/typescript
        run: npm clean-install

      - name: Execute Typescript tests
        working-directory: ./tests/typescript
        run: npm test

